name: Android
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - debug-armeabi-v7a
        - debug-arm64-v8a
        - release-armeabi-v7a
        - release-arm64-v8a
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo make _android_setup_root
        make _android_setup_user
    - name: Cache ~/.buildozer
      uses: actions/cache@v2
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}
    - name: Build
      run: make android-${{ matrix.target }}
    - name: Version
      run: touch VERSION_"$(git describe --always)"
    - uses: actions/upload-artifact@v2
      with:
        name: APK
        path: |
          bin/*.apk
          VERSION_*
